In [1]:
import numpy as np
import cema

### Generate the key and plain texts

In [2]:
keyLength=4 # 16-bytes, 128-bits
numPlainTexts=10

realKey = np.random.randint(256, size=keyLength)
print("Real key = ", realKey)

plainTexts = cema.genPlainTexts(keyLength, numPlainTexts)
#print(plainTexts.tolist())
#print(plainTexts)

Real key =  [118 118 119 226]


### Need a hypothesis matrix per each key byte
- if the key length is 4 bytes, we need 4 hypothesis matrices

In [3]:

H1 = cema.genHypoMatrix(plainTexts, 0)
print(H1)
H2 = cema.genHypoMatrix(plainTexts, 1)
#print(H2)
H3 = cema.genHypoMatrix(plainTexts, 2)
#print(H3)
H4 = cema.genHypoMatrix(plainTexts, 3)
#print(H4)

[[6 4 7 ... 2 5 6]
 [5 3 6 ... 1 6 5]
 [7 5 6 ... 3 4 7]
 ...
 [1 3 2 ... 5 4 1]
 [3 5 2 ... 7 2 3]
 [2 4 1 ... 6 3 2]]


In [4]:
hexValue = cema.getHexFromBitList(plainTexts.tolist()[0])
print(hexValue)
hexValue = cema.getHexFromBitList(plainTexts.tolist()[1])
print(hexValue)

ValueError: cannot reshape array of size 4 into shape (0,8)

### Generate dummy EM traces for testing

In [5]:
traceDuration=keyLength # since key length/plaintext length is 4, trace length is set to the same for time being

traceMatrix = cema.genEMTraces(realKey, plainTexts, traceDuration)
print(traceMatrix)

[[5 5 4 6 3 6 6 7 2 5]
 [5 4 6 5 1 2 4 4 3 3]
 [4 2 4 4 6 2 3 4 4 3]
 [3 5 5 1 4 5 5 2 2 5]]


### Recovering the key

In [6]:
C1 = cema.buildCorrelationMatrix(H1, traceMatrix)
(keyByte1, byteIndex) = np.unravel_index(C1.argmax(), C1.shape)

C2 = cema.buildCorrelationMatrix(H2, traceMatrix)
(keyByte2, byteIndex) = np.unravel_index(C2.argmax(), C2.shape)

C3 = cema.buildCorrelationMatrix(H3, traceMatrix)
(keyByte3, byteIndex) = np.unravel_index(C3.argmax(), C3.shape)

C4 = cema.buildCorrelationMatrix(H4, traceMatrix)
(keyByte4, byteIndex) = np.unravel_index(C4.argmax(), C4.shape)

guessedKey = [keyByte1, keyByte2, keyByte3, keyByte4]

print("Real key = ", realKey)
print("Guessed key = ", guessedKey)

Real key =  [118 118 119 226]
Guessed key =  [118, 118, 119, 226]
